### ISSUE TITLE
add an argument to specify the input file

### ISSUE THREAD

**Issue by CWempe** [wader/inkmake#4]
Great tool.
Exactly what I needed.

Just a little feature request.
How about adding a command line argument like "--inputfile example.svg"?

I am using an inkfile that generates different png files with a different subset of layers from a single svg.
So I need to specify the same input file in each line.

```
output_01.png input.svg -* +Layer1 + Layer3 +Layer17
output_02.png input.svg -* +Layer1 + Layer3 +Layer18
output_03.png input.svg -* +Layer1 + Layer4 +Layer8
[..]
```

It would be nice if I could change the input file with just one argument instead of opening the inkfile and search/replace the old input file name for the new one.

Another option would be to allow variable declaration inside the inkfile.
But that might be to diffucult to implement. :)

**Comment by wader** [comment]
Glad you like it! and I will think about the feature.
A workaround i guess would be to organize your input.svg files into different directories but have a common Inkfile and specify `--svg` and `--out`. You could also do a hack like `inkmake -s $PWD -o $PWD  <(sed s/input.svg/input2.svg/g Inkfile)`

**Comment by CWempe** [comment]
Thanks.
Having multiple inkfiles in different folders solves my problem.

**Comment by wader** [comment]
Ok! i was thinking that you might be able to have just one Inkfile but run inkmake with `-s` and `-o` to change source and output path. Another way i guess would be to have the Inkfile in each directory be a symlink to ../Inkfile etc.
