### ISSUE TITLE
options have to be separated by single spaces

### ISSUE THREAD

**Issue by CWempe** [wader/inkmake#7]
I am not sure if this is a small or big bug.
But it looks like the options inside the inkfile have to be separated by single spaces now (v0.1.5).

It definitely worked with more spaces before (v0.1.2?)

Example (not working):

```
test_out.png  test.svg
```

Error: `Unknown column ""`

Example (working):

```
test_out.png test.svg
```

I am having some more trouble with inkmake at the moment, but that might be an issue on my end.

**Comment by wader** [comment]
Hi, this should be fixed in master now. Could you give it a try?

**Comment by CWempe** [comment]
I am afraid I cannot try this.
At least not better than the example above or the test you implemented.

Like mentioned in the other issue my original inkfile does not work at the moment.

Maybe I can invest some time next week.

**Comment by wader** [comment]
Ok understand, no stress. Is it because complicated to test non-release? I'll see if i can get some windows dev env up and running in virtualbox etc and try to reproduce.

**Comment by CWempe** [comment]
>  Is it because complicated to test non-release?

I guess I could just download and replace `C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb`
Right?
